name: 3LivesSMP
main: me.sparklee.threeLives.ThreeLivesSMP
version: 1.0
api-version: 1.21
author: Sparklee

commands:
  threelives:
    description: 3LivesSMP main command
    usage: /threelives <lives|revive|reload>
    aliases: [revive, lives, threelivesreload]
  revive:
    description: Revive a banned player using a Revive Crystal
    usage: /revive <player>
  lives:
    description: Check your remaining lives
    usage: /lives
  threelivesreload:
    description: Reload 3LivesSMP configuration
    usage: /threelivesreload

permissions:
  threelives.reload:
    description: Allows reloading of 3LivesSMP config
    default: op
