name: LivesSMP
main: me.sparklee.LivesSMP.LivesSMP
version: 2.0.3
api-version: 1.21
author: Sparklee

commands:
  livessmp:
    description: LivesSMP main command
    usage: /livessmp <lives|revive|reload>
    aliases: [revive, lives, livessmpreload]
  revive:
    description: Revive a banned player using a Revive Crystal
    usage: /revive <player>
  lives:
    description: Check your remaining lives
    usage: /lives
  livessmpreload:
    description: Reload 3LivesSMP configuration
    usage: /livessmpreload
  addlives:
    description: Add lives to a player
    usage: /addlives <player> <amount>
  setlives:
    description: Set the lives of a player
    usage: /setlives <player> <amount>
  removelives:
    description: Remove lives from a player
    usage: /removelives <player> <amount>
  checklives:
    description: Check another player’s lives
    usage: /checklives <player>
  toplives:
    description: Shows the top players with the most lives
    usage: /toplives

permissions:
  livessmp.admin:
    description: Allows managing player lives (add/set/remove)
    default: op
  livessmp.bypass:
    description: Prevents life loss and bans from LivesSMP
    default: op
  livessmp.check:
    description: Allows checking other players' lives
    default: op

